# Generated by Django 5.0.4 on 2024-04-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('capital', models.CharField(max_length=15)),
                ('population', models.IntegerField()),
                ('square', models.IntegerField()),
                ('language', models.CharField(max_length=15)),
                ('description', models.TextField()),
            ],
        ),
    ]
