# Generated by Django 5.0.4 on 2024-04-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infocountry', '0002_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
