# Generated by Django 5.0.4 on 2024-04-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infocountry', '0003_country_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
