# Generated by Django 5.0.4 on 2024-04-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infocountry', '0004_alter_country_name_alter_country_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='language',
            field=models.CharField(max_length=100),
        ),
    ]
